//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examination_System
{
    using System;
    
    public partial class Generate_Exam_Result1
    {
        public Nullable<int> Exam_Id { get; set; }
        public int Question_ID { get; set; }
        public int Course_ID { get; set; }
        public string Question { get; set; }
        public Nullable<int> Type_ID { get; set; }
        public string Choice { get; set; }
    }
}
